
services:
  spring-app-student1:
    build:
      context: .
      dockerfile: Dockerfile
    image: ${DOCKERHUB_USERNAME}/spring-app-student1:latest
    container_name: spring-app-student1
    ports:
      - ${APP_PORT:-9001}:${APP_PORT:-9001}
    env_file:
      - .env
    restart: always
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "wget --quiet --tries=1 --spider http://localhost:$${APP_PORT:-9000}/actuator/health || exit 1",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - be_classroom_net


networks:
  be_classroom_net:
    external: true

