version: "3.9"

services:
  reesky-student1:
    build:
      context: .
      dockerfile: Dockerfile
    image: ${DOCKERHUB_USERNAME}/reesky-student1:latest
    container_name: reesky-student1
    ports:
      - "${APP_PORT:-9001}:${APP_PORT:-9001}"
    env_file:
      - .env
    restart: always
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "wget --quiet --tries=1 --spider http://localhost:${APP_PORT:-9001}/actuator/health || exit 1"
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - be_classroom_net

networks:
  be_classroom_net:
    external: true